## OAuth valid response (object)

    + `access_token`: `eyJhbGciOiJIUzI1NiJ9.e30.XmNK3GpH3Ys_7wsYBfq4C3M6goz71I7dTgUkuIa5lyQ` (string, required) - valid JWT
    + `expires_in`: 300 (number, required)
    + `token_type`: Bearer (string, required)