FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# EZSend

The EZCorp API is a REST-based API and covers three main functional areas: Accounts, Stores, and Admin. All amounts are in respective account/store local currencies, and not underlying token values.

:[EZSend Account Api](account/index.apib)

:[EZSend Store Api](store/index.apib)

:[EZSend Admin Api](admin/index.apib)