# Group Accounts
The account endpoints require an account id parameter which is a free-form string containing the digits (and only the digits) of the account phone number, including country/calling code, e.g. 14159442000, or 521551234. The format should be E.164, without the leading + symbol. All account endpoints are subject to rate limits associated with the given account id.

## Account [/accounts/{account_id}]

+ Parameters
    + account_id: `19876543219` (string) - The users phone number.

+ Model (application/json)
    ```
        :[Account Model](model.json)
    ```

### Retrieve Account [GET]
Retrieves the account associated with {account_id}. The returned balance will be in the account's respective currency.

+ Request 
    + Headers
        ```
            Authorization: Bearer JWT
        ```

+ Response 200

    [Account][]

+ Response 401
    ```
        Unauthorized: Missing or invalid access token
    ```
+ Response 403
    ```
        Forbidden - The supplied access token is not authorized for the given account
    ```
+ Response 409
    ```
        Conflict - Account has not yet been confirmed
    ```

### Create Account [PUT]
The balance and confiemd fields will be ignored, this is just a model test.

+ Request

    [Account][]

+ Response 204
+ Response 400
    ```
        {account_id} was malformed
    ```
+ Response 409
    ```
        Account already confirmed
    ```
+ Response 429

## Confirm Account [/accounts/{account_id}/confirm]
Confirms the account associated with <account_id> using the given <confirmation_code> which must match the current generated confirmed code and be within the allotted period.

+ Parameters
    + account_id: `19876543219` (string) - The id of the Store.

### Confirm Account [POST]
+ Request (application/json)
    + Body
        ```
            :[Confirm account body](confirmation-code-body.json)
        ```

+ Response 204
+ Response 403
    ```
        The supplied confirmation code is not valid
    ```
+ Response 409
    ```
        Account already confirmed
    ```

## Send Confirmation code [/accounts/<account_id>/sms]
Sends an SMS for authentication to <account_id>.  SMS contains a one-time-use authentication code that is generated and valid for a limited period only (default: 15m). 

### Send Confirmation Code [POST]
+ Response 204
+ Response 409
    ```
        Account has not yet been confirmed
    ```
  
## Authenticate [/accounts/<account_id>/auth]
Authenticates the account associated with the given <account_id> using the given <authentication_code> which must match the currently generated authentication code and be within the allotted period.  Successful authentication returns an access token to be used as a Bearer token on authenticated endpoints.  Note that no refresh token is returned and the refresh grant type is not supported.

### Authenticate [POST]
+ Request
    + Body
        ```
            :(Authentication body)[request-body.json]
        ```
        
+ Response 200
    + Body
        ```
            :(Authentication response body)[response-body.json]
        ```
+ Response 403
    ```
        The supplied authentication code is not valid
    ```
+ Response 409
    ```
        Account has not yet been confirmed
    ```

## Transfer [/accounts/<account_id>/transfer]
Transfers the given <amount> from the source account associated with <account_id> to the given target account, with optional memo.  The given <amount> is assumed to be in the currency respective to the source account.  If the target account does not exist, it will first be created with 0 balance (and empty name/zip fields).

+ Model
    ```
        :(Transfer Model)[transfer-model.json]
    ```

### Transfer [POST]

+ Request
    + Headers
        ```
            Authorization: Bearer JWT
        ```
    + Body
        ```
            :[Transfer body](transfer-body.json)
        ```
+ Response 200

    [Transfer][]

+ Response 400
    ```
        {
            "code": "InsufficientFunds",
            "message": "The source account has insufficient funds."
        }
    ```   
+ Response 400 
    ```
        {
            "code": "IncorrectName",
            "message": "The given name does not match that on the target account."
        }
    ```
+ Response 401
    ```
        Missing or invalid access token
    ```
+ Response 403
    ```
        The supplied access token is not authorized for the given account
    ```
+ Response 409
    ```
        Source account has not yet been confirmed
    ```